[32m2023-04-23 22:43:35 +0100[0m - dagster - [34mDEBUG[0m - etl - 96e3923c-83f2-447d-bf9c-2b6941ccebfc - 15105 - LOGS_CAPTURED - Started capturing logs in process (pid: 15105).
[32m2023-04-23 22:43:35 +0100[0m - dagster - [34mDEBUG[0m - etl - 96e3923c-83f2-447d-bf9c-2b6941ccebfc - 15105 - extract_census_data - STEP_START - Started execution of step "extract_census_data".
[32m2023-04-23 22:43:35 +0100[0m - dagster - [34mDEBUG[0m - etl - 96e3923c-83f2-447d-bf9c-2b6941ccebfc - 15105 - extract_census_data - STEP_INPUT - Got input "start" of type "Bool". (Type check passed).
[32m2023-04-23 22:43:38 +0100[0m - dagster - [34mDEBUG[0m - etl - 96e3923c-83f2-447d-bf9c-2b6941ccebfc - 15105 - extract_census_data - STEP_OUTPUT - Yielded output "result" of type "CensusDataFrame". Warning! Type check failed.
[32m2023-04-23 22:43:39 +0100[0m - dagster - [34mERROR[0m - [31metl - 96e3923c-83f2-447d-bf9c-2b6941ccebfc - 15105 - extract_census_data - STEP_FAILURE - Execution of step "extract_census_data" failed.

dagster._core.errors.DagsterTypeCheckDidNotPass: Type check failed for step output "result" - expected type "CensusDataFrame". Description: Required column JNYear-2001 not in dataframe with columns Index(['_id', 'GeoFIPS', 'GeoName', 'Region', 'IndustryClassification',
       'Description', 'Unit', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019', '2020', '2021'],
      dtype='object')

Stack Trace:
  File "/home/ste/anaconda3/envs/etl/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_plan.py", line 269, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/home/ste/anaconda3/envs/etl/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 386, in core_dagster_event_sequence_for_step
    for evt in _type_check_and_store_output(step_context, user_event):
  File "/home/ste/anaconda3/envs/etl/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 436, in _type_check_and_store_output
    for output_event in _type_check_output(step_context, step_output_handle, output, version):
  File "/home/ste/anaconda3/envs/etl/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 307, in _type_check_output
    raise DagsterTypeCheckDidNotPass(
[0m
